### PR TITLE
fix(ci): fix ci configuration

### PR DESCRIPTION
**Pull request by mjwwit**
The new TS build uses a very different testing setup.
This PR copies the config from aurelia/validation.

### CODE REVIEW

**Comment by mjwwit** [comment]
@jdanyow Can you check if this CI config works?

**Comment by mjwwit** [comment]
@EisenbergEffect can you by any chance check if this updated CI configuration works?

**Comment by EisenbergEffect** [comment]
Actually, I think @jdanyow may be the best person to check whether this is the expected configuration for our default TS setup for CI.

**Comment by mjwwit** [comment]
I did ask him, but it seems he can't get around to it. I've used the same config he made for validation.

**Comment by EisenbergEffect** [comment]
Ah, well, in that case....

**Comment by mjwwit** [comment]
https://circleci.com/gh/aurelia/testing/79 Yay! 🎉  🎊

**Comment by EisenbergEffect** [comment]
Yep. Looks good :)

**Pull request merged**
