### PR TITLE
chore(docs): update with catch and explanation

### PR DESCRIPTION
**Pull request by plwalters**
When `.create` fails for not being able to load a resource or something,
show how to show the errors.  Also add an explanation of when using
karma config why you don't need to use `src/` in the resource locator
path.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Can we extract the bit about `src` configuration out of the main flow and into a note. The reason for that is that it's actually not necessary with the CLI I don't think.

**Comment by EisenbergEffect** [comment]
@martingust Is there some way we could put out error messages without devs having to add the `catch` in every test?

**Comment by plwalters** [comment]
@EisenbergEffect Sorry just saw this comment, sure I'll move the `src` into it's own note.  As far as `catch` I think we should be able to do this but in the interim may be nice to have it in place and open a new issue with that in it.  I'll do that now

**Comment by plwalters** [comment]
https://github.com/aurelia/testing/issues/38

**Pull request closed without merging**
