### PR TITLE
Update docs to show catching errors

### PR DESCRIPTION
**Pull request by plwalters**
Related to #35 and #38

### CODE REVIEW

**Comment by plwalters** [comment]
Note the `src` note is moved, it closed my other PR for some reason.

**Comment by EisenbergEffect** [comment]
@martingust Can you review this?

**Comment by EisenbergEffect** [comment]
@martingust or @jdanyow Can you review this?

**Comment by EisenbergEffect** [comment]
@jdanyow Can you review this?

**Comment by EisenbergEffect** [comment]
Ping @jdanyow and @martingust

**Comment by jdanyow** [comment]
looks good to me.

**Pull request merged**
