### PR TITLE
feat(component-tester): add waitForElement method and options

### PR DESCRIPTION
**Pull request by tkhyn**
It has been a bit long due to a busy week but here is the PR regarding enhancement proposal #28

I've tried to keep the doc addition concise but thorough enough, feel free to trim it if you feel it's too long. Maybe 3 examples is too much !

Of course, comments / improvement suggestions are welcome.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@martingust Can you review this PR?

**Comment by EisenbergEffect** [comment]
@martingust Any chance you can review this? @jdanyow Can you take a look?

**Comment by EisenbergEffect** [comment]
@martingust or @jdanyow Can you review?

**Comment by EisenbergEffect** [comment]
@jdanyow Can you look at this?

**Comment by EisenbergEffect** [comment]
Ping @jdanyow

**Comment by jdanyow** [comment]
Few feedback items / questions:

* The doc changes say to pass functions like `() => document.querySelector('.firstName')` to the new `waitForElement` function. Shouldn't this be more specific? Instead of executing the document's `querySelector` method it should be the view element's `querySelector` method right?
* Should waitForElement accept a string (the selector) instead of a function (or both)?
* Are the lint rules passing? For example, I see some `var` usage where we'd typically want to use ES6 `let` or `const`.

**Comment by tkhyn** [comment]
Thanks @jdanyow for the feedback

> The doc changes say to pass functions like () => document.querySelector('.firstName') to the new waitForElement function. Shouldn't this be more specific? Instead of executing the document's querySelector method it should be the view element's querySelector method right?

Possibly. The callback can call querySelector on any element, really. But in some cases, the queried element may not be inside the view element (e.g. context menu or tooltip attached to the `body` by a library), hence my example with document.querySelector.

> Should waitForElement accept a string (the selector) instead of a function (or both)?

The problem with passing a string only is that it is unclear which query method should actually be used (jQuery, querySelector, etc ...), and does not allow complex lookups. I agree that passing a callback is cumbersome when you have a very simple selector, but at least it is explicit.

> Are the lint rules passing?

I did not check that, but the answer will certainly be no as the 'no-var' rule is enabled in .eslintrc.json. I'll amend that. (I personally still tend to use `var` in ES6 to distinguish 'function scope' variables from others).

**Comment by jdanyow** [comment]
Makes sense- what do you think about overloading the method to accept a selector string or a function? Would that be useful or do you find that most of the time a function is required for tests that need `waitForElement` functionality?

**Comment by tkhyn** [comment]
My personal point of view is if I could simply use a string as the first argument I don't think I would use it in my current tests. I thought of using a string selector selector only at first, but realized it would rule out many use cases and preferred to have a consistent way of calling waitForElement (i.e. always with a callback). As I use jQuery I don't mind writing `() => $('selector')` for simple lookups. I also do not have to think about switching from selector string to callback if the lookup becomes simpler or more complex.

That said I have no issue with the idea of supporting a selector string to implicitly use `this.element.querySelector(selectorString)` if you think it is unlikely to create confusion. My only concern is it makes assumptions about where the lookup takes place (in the element rather than the document) and/or the type of lookup (querySelector vs querySelectorAll) and that may create confusion and/or require additional options.

I don't know, really. Maybe we can add that simple string selector handling and wait for some feedback. Happy to do that + document this week if you want.

**Comment by jdanyow** [comment]
Good points, I think you're right about the overload causing confusion.

Thinking about this some more... if the function is a utility that doesn't use any of the component instance's internals it might be more clear/flexible to export it from aurelia-testing instead of adding the utility function to the Component class.

What if we did this:

New methods on the component class:
* `component.waitForElement(selector: string): Promise<Element>`  (uses element.querySelector)
* `component.waitForElements(selector: string): Promise<NodeList>` (uses element.querySelectorAll)

New utility functions exported from aurelia-testing:
* `waitForDocumentElement(selector: string): Promise<Element>`  (uses document.querySelector)
* `waitForDocumentElements(selector: string): Promise<NodeList>` (uses document.querySelectorAll)
* `waitFor(selector: () => any): Promise<any>` (originally component.waitForElement... all preceding methods/functions use this internally).

This renames waitForElement to waitFor and makes it a utility function exported from aurelia-testing (because it can return anything and can be used independently).

What do you think?

We should get others to weigh in here- maybe this is overkill. @martingust @EisenbergEffect @PWKad

**Comment by tkhyn** [comment]
@jdanyow looks good to me, I agree with the main waitFor() + explicit shortcuts making use of querySelector[All]

**Comment by EisenbergEffect** [comment]
@jdanyow This sounds good to me. Let's go for it!

**Comment by tkhyn** [comment]
Ok, I'll add that to my todo-list then.

**Comment by tkhyn** [comment]
Done. If it looks fine (including the doc) I can rebase + squash and create another PR.

**Comment by jdanyow** [comment]
@tkhyn this looks really good. Could you run `gulp lint`- I think there might be some minor whitespace issues and places where `var` needs to be replaced with `let` or `const`.

Don't worry about squashing, it's easy for us to do that during the merge.

**Comment by tkhyn** [comment]
@jdanyow  Yes indeed regarding lint, I had well noted it earlier but forgot that. That's fixed with the latest commit.

**Pull request merged**
