### PR TITLE
chore(everything): refactor to TypeScript build

### LINKED ISSUE #72: Type inconsistency in waitFor, waitForElement, & waitForElements
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.0.1

**Please tell us about your environment:**
* **Operating System:**
Linux (Fedora 25)

* **Node Version:**
6.11.0

* **NPM Version:**
3.10.10

* **JSPM OR Webpack AND Version**
webpack 3.3.0

* **Browser:**
all
* **Language:**
all

**Current behavior:**
The type definition for [`waitForElement`](https://github.com/aurelia/testing/blob/1ecfbfecdc6059d51f2783ebfc454b64686f66a9/src/component-tester.js#L123), [`waitForElements`](https://github.com/aurelia/testing/blob/1ecfbfecdc6059d51f2783ebfc454b64686f66a9/src/component-tester.js#L127) and [`waitFor`](https://github.com/aurelia/testing/blob/1ecfbfecdc6059d51f2783ebfc454b64686f66a9/src/wait.js#L9) define the second `options` argument as required (`options: any`). The `ComponentTester`'s unit test suggests that the second argument is _optional_ as it [omits it entirely](https://github.com/aurelia/testing/blob/1ecfbfecdc6059d51f2783ebfc454b64686f66a9/test/component-tester.spec.js#L23). 

This inconsistent definition forces TypeScript users to unnecessarily pass in an empty object to satisfy the type definition, therefore I think the definition should be changed to `options?: any`.

This is reinforced by the [official docs](https://github.com/aurelia/testing/blob/fb642c1576cadd1cb5bf4dfe8c8a08e559aeb6b3/doc/article/en-US/testing-components.md#waiting-for-elements) which state the first argument, `selector`, as _mandatory_, but pose no such restriction on the `options` argument.

**Expected/desired behavior:**

* **What is the expected behavior?**
    - The type definition of the second argument (`options`) for the [`waitForElement`](https://github.com/aurelia/testing/blob/1ecfbfecdc6059d51f2783ebfc454b64686f66a9/src/component-tester.js#L123), [`waitForElements`](https://github.com/aurelia/testing/blob/1ecfbfecdc6059d51f2783ebfc454b64686f66a9/src/component-tester.js#L127), and the [`waitFor`](https://github.com/aurelia/testing/blob/1ecfbfecdc6059d51f2783ebfc454b64686f66a9/src/wait.js#L9) functions should be updated to make the `options` argument optional (i.e. `options?: any`).

* **What is the motivation / use case for changing the behavior?**
    - Consistent type definitions with example usage and existing technical documentation.
    - Avoid forcing TypeScript users to unnecessarily pass in an empty object as the argument.

### PR DESCRIPTION
**Pull request by mjwwit**
- Use TS build from aurelia/validation
- Refactor project to TypeScript, including linter fixes
- Fix incorrect typings for `waitFor`, `waitForElement`, and `waitForElements` (#72)
- Add missing typing for `ComponentTester.detached`
- Fix incorrect return types for `bind`, `attached`, and `unbind` (return value is a `Promise`)
- Make `ComponentTester` generic, so a contained view-model type can be passed in
- Fix return type of `dispose`
- Change `bindingContext` type from any to `{}`, as it has to be an `Object`
- Add Karma middleware to serve templates
- Update README.md to reflect build changes

Closes #72, possible breaking changes for TypeScript users

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Well, that was fast! 🥇 
@jdanyow Can you do a review of the TS project setup?
@mjwwit Just to confirm, besides improving the typings themselves, this doesn't include any breaking changes to the js API or behavior does it?

**Comment by mjwwit** [comment]
I like fast. And no, no API changes have been made.

**Comment by mjwwit** [comment]
@jdanyow @EisenbergEffect I'm willing to refactor more of Aurelia's codebase to TypeScript, but I want to know if this is the way to go.

**Comment by EisenbergEffect** [comment]
We'd love to have your assistance in this. @jdanyow Can you review and provide feedback? @mjwwit is interested in helping us convert more to TypeScript and wants to have your sign-off that this is the right way.

**Comment by mjwwit** [comment]
As the PR has been merged I take it this is the way to go. Are there any projects you'd like me to migrate first, or should I just start with whatever I like?
Will we be working in typescript-port branches in other projects as well? If so, can you create these branches so I can submit PRs?

**Comment by EisenbergEffect** [comment]
I think it would be best to start with some small ones for which there might be high return on investment. What about doing the event-aggregator next? I think the APIs could be made nicer for TypeScript users providing good value there. Let's go one at a time and see how it goes. Thoughts?

**Comment by mjwwit** [comment]
Works for me. I'll do event-aggregator next then. Can you create a branch there?

**Comment by EisenbergEffect** [comment]
Here you go!

https://github.com/aurelia/event-aggregator/tree/typescript-port

**Comment by gheoan** [comment]
@mjwwit It would be nice if the PRs could be made more incremental with multiple commits, so that each commit can be reviewed individually. There could be a commit where the files are renamed to the ts extension, one were the missing types are added and so on.

@EisenbergEffect I would like to help convert the route-recognizer library to typescript too. There is a bit of code there which is missing types and I think I already have a local branch which adds the missing types. What do you think?

**Comment by mjwwit** [comment]
@gheoan Splitting it up doesn't make sense to me, as the parts don't work/compile/build by themselves. How would it help the reviewing process? In the end its the same changes... I'd love to explain the process of migrating if that's what you're looking for.

Either way, this is getting way off topic for this PR, maybe it's a good idea to continue migration talk on Discourse.

**Comment by gheoan** [comment]
@mjwwit With a single commit the github diff interface only shows that the whole `src/aurelia-testing.js` file was removed and that `src/aurelia-testing.ts` was added. This makes it hard to spot changes to the code itself such that the import declarations were changed in `aurelia-testing.ts`. Commits should be as small as possible, so that the commit can be reverted or tracked down in the history. However, do not feel obligated to do this as it is only a recommendation.

Thank you for working on typescript conversion and sorry for the offtopic.

**Comment by EisenbergEffect** [comment]
I think this worked out well enough for us. We were able to review and glad to have the contributions from @mjwwit.

**Pull request merged**
