### PR TITLE
feat(component-tester) first working version (based on webpack)

### PR DESCRIPTION
**Pull request by sylvain-hamel**
This PR is a first working version of `ComponentTester` and includes :
- The `ComponentTester` class
- A set of Aurelia specific jasmine matchers
- Files to help setup tests in an existing weback based project (`setup.js` and `test_index.js`)

A basic test using `ComponentTester` looks like this:

```
import {ComponentTester} from "./integrated/component-tester";
describe('User component', () => {

  it('should show user name', done => {

    ComponentTester.load({
      type: 'user',
      markup: `<user user.bind="currentUser"></user>`,
      setupBindingContext: (context, container)=> {
        context.currentUser = {
          login: 'defunkt',
          avatar_url: 'https://avatars.githubusercontent.com/u/2?v=3',
          html_url: 'https://github.com/defunkt',
        };
      }
    }).then(tester=> {
      let value = tester.$el.find('p.name');
      expect(value).toBeVisible();
      expect(value.text()).toBe('defunkt');
      tester.dispose(done);
    });

  });
});
```

Ref: https://github.com/aurelia/testing/issues/1

### CODE REVIEW

**Comment by sylvain-hamel** [comment]
@EisenbergEffect, @jdanyow, @martingust please review.

**Comment by axwalker** [comment]
Thanks a lot for this - it works as expected. I've chosen to remove jquery from this for my own use and instead just use `tester.element` in my assertions. This is partly because there's currently a clash between the typings for jquery and angular-protractor.

**Comment by martingust** [comment]
@sylvain-hamel Sorry for late response. I yet have to look into you PR more throughly. I've just created a  PR [here](https://github.com/aurelia/testing/pull/3) with support for lifecycle testing on the initial implementation. Let's see what ideas and implementations we can bring together to create something nice!

**Comment by EisenbergEffect** [comment]
I'm going to close this PR for now.
@sylvain-hamel Please take a look at master. @martingust had been working to implement a previously discussed and blogged design. The implementation is in now. We'd like to see if some of your ideas from this PR can augment the component testing piece with additional, helpful functionality. We want to be careful that we don't bring in any 3rd party dependencies though.

**Pull request closed without merging**
